### ISSUE TITLE
Error in log file: ripgrepPath not found

### ISSUE THREAD

**Issue by Kalmovic** [wallabyjs/console-ninja#53] opened 2022-12-15 13:30 UTC
I'm getting the following respinse from COnsole Ninja:

> Console Ninja is ⌛ waiting for webpack, and jest to start. Console Ninja has successfully integrated with webpack, and jest found in your project dependencies, but has not connected to a running instance of it yet.

Running locally doesnt make it change the status. Opening the log file, here's the message:

`ERR! extension `ripgrepPath` not found.`

Is there any configuration needed?

**Comment by ArtemGovorov** [comment] 2022-12-16 00:34
The error itself shouldn't stop the extension from working. Having said that, we'd like to understand why it's happening too.

The status means that the extension has integrated with the mentioned tools and is waiting for them to start. Does the status change when you start jest or webpack from CLI in your project? If not, can you please share some more details about your app/stack and share your `~/.console-ninja/trace.log` file?

Re: `ERR! extension ripgrepPath not found.` - what OS are you using and how/where do you have VS Code installed?

**Comment by ianyimi** [comment] 2022-12-19 18:24
I am also running into the exact same error messages as stated above. I am running a Vite app on Docker for Windows with WSL2. I'm using docker-compose to start the application. Here is both my package.json & how I start my project locally. Let me know if you need anymore info
![wsl console ninja 2](https://user-images.githubusercontent.com/41877924/208493519-21f31f22-7632-4a35-ab96-03c4992c6be3.png)

**Comment by ianyimi** [comment] 2022-12-19 20:30
An update: I was able to bypass this specific error by 

1. installing Microsoft's WSL VSCode extension
2. reopening my project in WSL 
3. reinstalling Console Ninja (in addition to most of my other extensions) in WSL

It is currently not registering my dependencies & I get this in the log file

![console ninja 3](https://user-images.githubusercontent.com/41877924/208515162-480d735e-267a-4eab-b3e5-f82f565bc4b2.png)

**Comment by smcenlly** [comment] 2022-12-20 03:51
We found a problem with `ripgrep` resolution on Windows machines. The problem is fixed in Console Ninja `v0.0.50`. Please update to the latest version, it will fix the problem.

**Closed by smcenlly** 2022-12-20 03:51 UTC
Labels: more info required
