### ISSUE TITLE
[Feature]: Support for Shopify CLI

### ISSUE THREAD

**Issue by trenkwill** [wallabyjs/console-ninja#305] opened 2024-05-24 11:21 UTC
### Describe the feature you'd like.

[Shopify CLI](https://shopify.dev/docs/themes/tools/cli)

**Comment by smcenlly** [comment] 2024-05-26 22:02
Closing as a duplicate of https://github.com/wallabyjs/console-ninja/issues/140.

**Closed by smcenlly** 2024-05-26 22:02 UTC
Labels: enhancement, requires triage
