### ISSUE TITLE
[Bug]: Not working with node 20.9.0

### ISSUE THREAD

**Issue by tuan-zigvy** [wallabyjs/console-ninja#225] opened 2023-11-02 03:53 UTC
### What happened?

When i update node version to 20 console-ninja not working with nestjs or express , Fe (react) is normal working, when back 18 it working with nestjs

### Version

v1.0.243

### Steps to reproduce (or sample repo)

sorry it I am working productionn. I thing not issue with product

### Log output

```shell
10:43:12.020 info buildHook-60339 installing build hook for webpack at /home/tuan-dd/repos/booking-api, node v18.18.2
10:43:12.032 info buildHook-60339 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:43:12.301 info host client connected: buildHook { address: '::', family: 'IPv6', port: 43159 }
10:43:12.033 info buildHook-60339 running tools: webpack
10:43:12.034 info buildHook-60339 installing fs interceptor
10:43:12.307 info buildHook-60339 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:43:12.307 info buildHook-60339 running tools: webpack
10:43:18.155 info buildHook-60339 file processed (sync): 3 log points, error handler: false
10:43:18.223 info buildHook-60339 file processed (sync): 0 log points, error handler: false
10:43:18.239 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:18.427 info buildHook-60339 file processed (sync): 0 log points, error handler: false
10:43:18.491 info buildHook-60339 file processed (sync): 0 log points, error handler: false
10:43:18.509 info buildHook-60339 file processed (sync): 0 log points, error handler: false
10:43:18.517 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:18.565 info buildHook-60339 file processed (sync): 3 log points, error handler: false
10:43:18.582 info buildHook-60339 file processed (sync): 0 log points, error handler: false
10:43:18.643 info buildHook-60339 file processed (sync): 2 log points, error handler: false
10:43:18.688 info buildHook-60339 file processed (sync): 14 log points, error handler: false
10:43:18.947 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:18.976 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:19.092 info buildHook-60339 file processed (sync): 0 log points, error handler: false
10:43:19.124 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:19.132 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:19.171 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:19.183 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:19.212 info buildHook-60339 file processed (sync): 0 log points, error handler: false
10:43:19.223 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:19.233 info buildHook-60339 file processed (sync): 0 log points, error handler: false
10:43:19.252 info buildHook-60339 file processed (sync): 3 log points, error handler: false
10:43:19.349 info buildHook-60339 file processed (sync): 6 log points, error handler: false
10:43:19.371 info buildHook-60339 file processed (sync): 2 log points, error handler: false
10:43:19.473 info buildHook-60339 file processed (sync): 7 log points, error handler: false
10:43:19.561 info buildHook-60339 file processed (sync): 9 log points, error handler: false
10:43:19.611 info buildHook-60339 file processed (sync): 4 log points, error handler: false
10:43:19.650 info buildHook-60339 file processed (sync): 12 log points, error handler: false
10:43:19.734 info buildHook-60339 file processed (sync): 5 log points, error handler: false
10:43:19.778 info buildHook-60339 file processed (sync): 19 log points, error handler: false
10:43:19.805 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:19.821 info buildHook-60339 file processed (sync): 4 log points, error handler: false
10:43:19.831 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:19.866 info buildHook-60339 file processed (sync): 1 log points, error handler: false
10:43:19.991 info buildHook-60339 file processed (sync): 4 log points, error handler: false
10:43:20.019 info buildHook-60339 file processed (sync): 6 log points, error handler: false
10:43:20.041 info buildHook-60339 file processed (sync): 0 log points, error handler: false
10:43:20.055 info buildHook-60339 file processed (sync): 2 log points, error handler: false
10:43:31.458 info host client disconnected: runtimeHook 1001
10:43:31.458 info host client disconnected: runtimeHook
10:43:31.461 info host client disconnected: runtimeHook 1001
10:43:31.461 info host client disconnected: runtimeHook
10:43:31.500 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 40455 }
10:43:32.052 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 40455 }
10:43:38.814 info extension stopping host
10:43:38.817 info host removing cache folder: 0b5b64d3172aa3168e7fe67ee041336d
10:43:38.836 info extension client disconnected: 1006 
10:43:38.837 info buildHook-60316 client disconnected: 1006 
10:43:38.837 info buildHook-60316 disconnected from host: 43159
10:43:38.837 info buildHook-60316 disconnected from all hosts
10:43:38.839 info buildHook-60328 client disconnected: 1006 
10:43:38.839 info buildHook-60328 disconnected from host: 43159
10:43:38.839 info buildHook-60328 disconnected from all hosts
10:43:38.928 info buildHook-60339 client disconnected: 1006 
10:43:38.928 info buildHook-60339 disconnected from host: 43159
10:43:38.928 info buildHook-60339 disconnected from all hosts
10:43:39.068 info extension host process output: port:[43159]
10:43:39.054 info host ------------ starting ------------
10:43:39.068 info extension 
10:43:39.079 info host client connected: extension { address: '::', family: 'IPv6', port: 43159 }
10:43:39.105 info host starting host: {"extensionFolder":"/home/tuan-dd/.vscode-server/extensions/wallabyjs.console-ninja-1.0.243","runtimeHookFile":"/home/tuan-dd/.vscode-server/extensions/wallabyjs.console-ninja-1.0.243/out/runtimeHook/tracer.js","globalErrorHandlerFile":"/home/tuan-dd/.vscode-server/extensions/wallabyjs.console-ninja-1.0.243/out/runtimeHook/errorHandler.js","filesToInstrument":[{"path":"/home/tuan-dd/repos/booking-api/lambdaFunctions/customMessage/handler.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/lambdaFunctions/preTokenGeneration/handler.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/email-templates/mailgun/list-templates.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/email-templates/mailgun/mailgun.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/guards/roles.guard.ts","autoLogPoints":[{"range":{"startLine":145,"endLine":145,"startColumn":48,"endColumn":48}}],"reason":"autoLogPoints"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/vendor-withdraw-policy/vendor-withdraw-policy.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/user/user.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/vendor-service/vendor-rate-request.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/vendor-service/vendor-service.resolver.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/notification/notification.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/base/base.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/flight-stats/flight-stats.service.ts","autoLogPoints":[{"range":{"startLine":88,"endLine":88,"startColumn":20,"endColumn":20}},{"range":{"startLine":98,"endLine":98,"startColumn":30,"endColumn":30}}],"reason":"autoLogPoints"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/airport/airport.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/flight-stats/flight-stats.controller.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/auth/auth.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/booking/booking.utils.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/booking/flight-itinerary.service.ts","autoLogPoints":[{"range":{"startLine":125,"endLine":125,"startColumn":33,"endColumn":33}}],"reason":"autoLogPoints"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/booking/booking.resolver.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/booking/holiday.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/booking/flight.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/booking/booking.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/booking/request-items.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/booking/consumer/payment-method-hold-funds.consumer.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/booking/consumer/request-item.consumer.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/invoice/invoice.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/stripe/stripe.resolver.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/stripe/stripe.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/cars/cars.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/withdraw-request/withdraw-request.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/discount/discount.resolver.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/discount/discount.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/shared/services/mailgun.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/common/utils.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/interceptors/typeorm-logger-interceptor.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/interceptors/auth-user-interceptor.service.ts","reason":"search"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/auth/auth.resolver.ts","autoLogPoints":[{"range":{"startLine":98,"endLine":98,"startColumn":28,"endColumn":28}}],"reason":"autoLogPoints"},{"path":"/home/tuan-dd/repos/booking-api/src/common/dto/CommonPageResponse.ts","autoLogPoints":[{"range":{"startLine":21,"endLine":21,"startColumn":20,"endColumn":20}}],"reason":"autoLogPoints"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/stripe/stripe.utils.ts","autoLogPoints":[{"range":{"startLine":31,"endLine":31,"startColumn":14,"endColumn":14}}],"reason":"autoLogPoints"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/user/user.resolver.ts","reason":"open"},{"path":"/home/tuan-dd/repos/booking-api/src/modules/vendor/vendor.service.ts","reason":"open"},{"path":"/home/tuan-dd/repos/booking-api/src/common/constants/entity.ts","reason":"open"},{"path":"/home/tuan-dd/repos/booking-api/src/common/constants/mode-query.enum.ts","reason":"open"}],"debug":false,"config":{"dateTimeFormat":"HH:mm:ss.SSS","dateTimeDisplayMode":"Absolute","installBinToPath":true,"openLinksInEditor":true,"maxLogViewerEntries":2500000,"fontSize":12,"autoClearLogViewerOnFileChanges":true,"outputMode":"In View","captureFunctions":false,"searchUrl":"https://www.google.com/search?q={query}","enableProFeatures":true,"toolsToAutoPatch":["vite","jest","webpack","next.js","nest.js","cypress","http-server","serve","live-server","nuxt","remix","qwik","hydrogen","serverless","astro"],"showErrors":true,"showLogsOnlyFromOpenedFiles":false,"showLogsFromLogPointsOnly":false,"showLogsFromMultipleRunningToolsTogether":false},"allowedHosts":["localhost","127.0.0.1","example.cypress.io","Tuan-dd","172.17.21.154"],"host":"localhost"}
10:43:39.147 info host starting tools discovery and integration
10:43:39.155 info host looking for tools to patch
10:43:39.227 info host worker Starting Host Worker...
10:43:39.779 info host found 5 tool file(s) to patch
10:43:39.783 info host patching /home/tuan-dd/repos/booking-api/node_modules/@nestjs/cli/actions/start.action.js
10:43:39.784 info host patching /home/tuan-dd/repos/booking-api/node_modules/webpack/lib/index.js
10:43:39.784 info host patching /home/tuan-dd/repos/booking-api/node_modules/webpack/lib/webpack.js
10:43:39.784 info host patching /home/tuan-dd/repos/booking-api/node_modules/jest/bin/jest.js
10:43:39.784 info host patching /home/tuan-dd/repos/booking-api/node_modules/jest-runner/build/testWorker.js
10:43:39.839 info host completed tools discovery and integration
10:43:39.948 info buildHook-60316 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:43:39.949 info buildHook-60316 running tools: node
10:43:39.957 info host client connected: buildHook { address: '::', family: 'IPv6', port: 43159 }
10:43:39.958 info buildHook-60316 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:43:39.959 info buildHook-60316 running tools: node
10:43:40.526 info buildHook-60328 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:43:40.526 info buildHook-60328 running tools: node
10:43:40.529 info host client connected: buildHook { address: '::', family: 'IPv6', port: 43159 }
10:43:40.530 info buildHook-60328 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:43:40.530 info buildHook-60328 running tools: node
10:43:42.394 info buildHook-60339 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:43:42.394 info buildHook-60339 running tools: webpack
10:43:42.437 info host client connected: buildHook { address: '::', family: 'IPv6', port: 43159 }
10:43:42.439 info buildHook-60339 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:43:42.439 info buildHook-60339 running tools: webpack
10:43:42.507 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:42.519 info buildHook-60339 file processed (stat): 0 log points, error handler: false
10:43:42.581 info buildHook-60339 file processed (stat): 0 log points, error handler: false
10:43:42.641 info buildHook-60339 file processed (stat): 0 log points, error handler: false
10:43:42.656 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:42.669 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:42.677 info buildHook-60339 file processed (stat): 0 log points, error handler: false
10:43:42.687 info buildHook-60339 file processed (stat): 0 log points, error handler: false
10:43:42.702 info buildHook-60339 file processed (stat): 6 log points, error handler: false
10:43:42.740 info buildHook-60339 file processed (stat): 4 log points, error handler: false
10:43:42.751 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:42.798 info buildHook-60339 file processed (stat): 2 log points, error handler: false
10:43:42.811 info buildHook-60339 file processed (stat): 3 log points, error handler: false
10:43:42.905 info buildHook-60339 file processed (stat): 7 log points, error handler: false
10:43:42.918 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:42.933 info buildHook-60339 file processed (stat): 2 log points, error handler: false
10:43:43.021 info buildHook-60339 file processed (stat): 6 log points, error handler: false
10:43:43.028 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:43.107 info buildHook-60339 file processed (stat): 9 log points, error handler: false
10:43:43.140 info buildHook-60339 file processed (stat): 12 log points, error handler: false
10:43:43.169 info buildHook-60339 file processed (stat): 19 log points, error handler: false
10:43:43.225 info buildHook-60339 file processed (stat): 5 log points, error handler: false
10:43:43.239 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:43.270 info buildHook-60339 file processed (stat): 14 log points, error handler: false
10:43:43.273 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:43.284 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:43.314 info buildHook-60339 file processed (stat): 4 log points, error handler: false
10:43:43.323 info buildHook-60339 file processed (stat): 4 log points, error handler: false
10:43:43.337 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:43.348 info buildHook-60339 file processed (stat): 3 log points, error handler: false
10:43:43.357 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:43.363 info buildHook-60339 file processed (stat): 0 log points, error handler: false
10:43:43.373 info buildHook-60339 file processed (stat): 2 log points, error handler: false
10:43:43.405 info buildHook-60339 file processed (stat): 3 log points, error handler: false
10:43:43.415 info buildHook-60339 file processed (stat): 1 log points, error handler: false
10:43:43.497 info buildHook-60339 file processed (stat): 0 log points, error handler: false
10:43:43.517 info buildHook-60339 file processed (stat): 0 log points, error handler: false
10:43:43.517 info buildHook-60339 file processed (stat): 0 log points, error handler: false
10:43:51.906 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 43159 }
10:44:11.869 info buildHook-61852 installing build hook for node at /home/tuan-dd/repos/booking-api, node v20.9.0
10:44:11.880 info buildHook-61852 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:44:11.880 info buildHook-61852 running tools: node
10:44:12.065 info host client connected: buildHook { address: '::', family: 'IPv6', port: 43159 }
10:44:11.881 info buildHook-61852 installing fs interceptor
10:44:12.070 info buildHook-61852 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:44:12.070 info buildHook-61852 running tools: node
10:44:12.317 info buildHook-61869 installing build hook for node at /home/tuan-dd/repos/booking-api, node v20.9.0
10:44:12.330 info buildHook-61869 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:44:12.363 info host client connected: buildHook { address: '::', family: 'IPv6', port: 43159 }
10:44:12.330 info buildHook-61869 running tools: node
10:44:12.332 info buildHook-61869 installing fs interceptor
10:44:12.368 info buildHook-61869 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:44:12.369 info buildHook-61869 running tools: node
10:44:12.940 info buildHook-61884 installing build hook for webpack at /home/tuan-dd/repos/booking-api, node v20.9.0
10:44:12.955 info buildHook-61884 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:44:12.955 info buildHook-61884 running tools: webpack
10:44:13.175 info host client connected: buildHook { address: '::', family: 'IPv6', port: 43159 }
10:44:12.957 info buildHook-61884 installing fs interceptor
10:44:13.180 info buildHook-61884 allowed tools: vite, jest, webpack, next.js, nest.js, cypress, http-server, serve, live-server, nuxt, remix, qwik, hydrogen, serverless, astro, node
10:44:13.180 info buildHook-61884 running tools: webpack
10:44:27.101 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:27.188 info buildHook-61884 file processed (stat): 3 log points, error handler: false
10:44:27.195 info buildHook-61884 file processed (stat): 0 log points, error handler: false
10:44:27.210 info buildHook-61884 file processed (stat): 2 log points, error handler: false
10:44:27.242 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:27.291 info buildHook-61884 file processed (stat): 0 log points, error handler: false
10:44:27.293 info buildHook-61884 file processed (stat): 0 log points, error handler: false
10:44:27.306 info buildHook-61884 file processed (stat): 0 log points, error handler: false
10:44:27.329 info buildHook-61884 file processed (stat): 0 log points, error handler: false
10:44:27.346 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:27.424 info buildHook-61884 file processed (stat): 2 log points, error handler: false
10:44:27.446 info buildHook-61884 file processed (stat): 3 log points, error handler: false
10:44:27.581 info buildHook-61884 file processed (stat): 7 log points, error handler: false
10:44:27.602 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:27.622 info buildHook-61884 file processed (stat): 2 log points, error handler: false
10:44:27.804 info buildHook-61884 file processed (stat): 6 log points, error handler: false
10:44:27.810 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:27.986 info buildHook-61884 file processed (stat): 9 log points, error handler: false
10:44:28.003 info buildHook-61884 file processed (stat): 4 log points, error handler: false
10:44:28.035 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:28.049 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:28.080 info buildHook-61884 file processed (stat): 6 log points, error handler: false
10:44:28.128 info buildHook-61884 file processed (stat): 4 log points, error handler: false
10:44:28.234 info buildHook-61884 file processed (stat): 5 log points, error handler: false
10:44:28.240 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:28.261 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:28.308 info buildHook-61884 file processed (stat): 14 log points, error handler: false
10:44:28.314 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:28.443 info buildHook-61884 file processed (stat): 0 log points, error handler: false
10:44:28.453 info buildHook-61884 file processed (stat): 0 log points, error handler: false
10:44:28.515 info buildHook-61884 file processed (stat): 0 log points, error handler: false
10:44:28.551 info buildHook-61884 file processed (stat): 0 log points, error handler: false
10:44:28.561 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:28.602 info buildHook-61884 file processed (stat): 4 log points, error handler: false
10:44:28.629 info buildHook-61884 file processed (stat): 1 log points, error handler: false
10:44:28.641 info buildHook-61884 file processed (stat): 3 log points, error handler: false
10:44:28.715 info buildHook-61884 file processed (stat): 12 log points, error handler: false
10:44:28.748 info buildHook-61884 file processed (stat): 19 log points, error handler: false
10:44:31.279 info extension stopping host
10:44:31.302 info buildHook-61852 client disconnected: 1006 
10:44:31.303 info buildHook-61852 disconnected from host: 43159
10:44:31.303 info buildHook-61852 disconnected from all hosts
10:44:31.306 info extension client disconnected: 1006 
10:44:31.304 info buildHook-61869 client disconnected: 1006 
10:44:31.304 info buildHook-61869 disconnected from host: 43159
10:44:31.305 info buildHook-61869 disconnected from all hosts
10:44:31.316 info buildHook-61884 client disconnected: 1006 
10:44:31.316 info buildHook-61884 disconnected from host: 43159
10:44:31.317 info buildHook-61884 disconnected from all hosts
10:44:31.592 info extension host process output: port:[43159]
10:44:31.592 info extension
```

**Comment by ArtemGovorov** [comment] 2023-11-02 07:18
Thanks for posting the issue. It was caused by a breaking change in node.js. The issue is now fixed and the fix is published in v1.0.249+.

**Closed by ArtemGovorov** 2023-11-02 07:18 UTC
Labels: bug, requires triage
