### ISSUE TITLE
[Bug]:  logpoint make error

### ISSUE THREAD

**Issue by tuan-zigvy** [wallabyjs/console-ninja#229] opened 2023-11-15 09:14 UTC
### What happened?

When i use logpoint with arguments in arrow functions without return , It will make error and not show log

 
![image](https://github.com/wallabyjs/console-ninja/assets/139092565/54db2ea1-49c8-427e-a5a6-98744c225c4d)

if I use with return , It work normally 

![image](https://github.com/wallabyjs/console-ninja/assets/139092565/ff5762df-5af8-4b55-9633-0853aa7fff5d)

Node: 20
Vite: 4.2.0

### Version

last

### Steps to reproduce (or sample repo)

no

### Log output

```shell
no
```

**Comment by ArtemGovorov** [comment] 2023-11-15 10:28
> It will make error and not show log

What error does it show?

The scenario should be supported by Console Ninja and it's working for us in sample repos. Can you please create a GH repo with a reproducible example of the issue? We are happy to investigate and fix it.

**Comment by ArtemGovorov** [comment] 2023-11-15 10:37
Please ignore my previous comment. We have reproduced the issue and are working on a fix.

**Comment by ArtemGovorov** [comment] 2023-11-15 11:14
The issue is now fixed and the fix is published in v1.0.256+.

**Closed by ArtemGovorov** 2023-11-15 11:14 UTC
Labels: bug

**Comment by tuan-zigvy** [comment] 2023-11-20 03:38
Thank team every much
