### ISSUE TITLE
[Feature]: Allow wildcard in the host subdomain

### ISSUE THREAD

**Issue by omerson-cruz** [wallabyjs/console-ninja#331] opened 2024-08-14 06:59 UTC
### Describe the feature you'd like.

I'm not sure if this is already supported but currently I'm testing a website 
with multiple subdomain. (I'm testing it locally) 
like for example *.mydomain.com

Could you please add this kind of feature? 

Thank you

**Comment by smcenlly** [comment] 2024-08-14 22:13
Closing as a duplicate of https://github.com/wallabyjs/console-ninja/issues/325#issuecomment-2261790921

**Closed by smcenlly** 2024-08-14 22:13 UTC
Labels: enhancement, requires triage
