### ISSUE TITLE
[Feature]: Send log directly to the Log Viewer

### ISSUE THREAD

**Issue by namphamdev** [wallabyjs/console-ninja#230] opened 2023-11-16 04:57 UTC
### Describe the feature you'd like.

Console Ninja doesn't support React Native, but I like to work with Console ninja log viewer. Is there any way to send the log directly to the logviewer? via API or Socket, then I can write a function to send and explore the log data on log viewer

**Comment by smcenlly** [comment] 2023-11-16 22:46
No, it's not possible to send a value directly to Console Ninja. There's a non-trivial communication channel that is established between Console Ninja and your development runtime. For security/privacy reasons, this is also limited (by default) to local host.

To expose something in the React Native runtime, we'd need to expand our integration. 

Closing this issue as it is in essence a duplicate of https://github.com/wallabyjs/console-ninja/issues/6.

**Closed by smcenlly** 2023-11-16 22:45 UTC
Labels: enhancement, requires triage
