### ISSUE TITLE
[Bug]: Getting errors in browser console after uninstalling

### ISSUE THREAD

**Issue by subhasish-smiles** [wallabyjs/console-ninja#92] opened 2023-01-21 20:05 UTC
### What happened?

![Screenshot from 2023-01-22 01-32-11](https://user-images.githubusercontent.com/113948763/213885057-e863eefb-d6ed-4768-aa9c-8d59a8782195.png)
Getting these error messages in browser console after uninstalling the vscode extension.

### Version

0.0.70

### Steps to reproduce (or sample repo)

Install in vscode then uninstall it. It should not leave errors messages after it is removed. It should provide a way how to get rid of the errors. 

### Log output

```shell
not applicable
```

**Comment by ArtemGovorov** [comment] 2023-01-22 09:18
This is a duplicate of https://github.com/wallabyjs/console-ninja/issues/9 opened issue, you may find a [solution here](https://github.com/wallabyjs/console-ninja/issues/9#issuecomment-1343698142).

**Closed by ArtemGovorov** 2023-01-22 09:18 UTC
Labels: bug, requires triage
