### ISSUE TITLE
[Feature]: Solid.js support

### ISSUE THREAD

**Issue by kevinseabourne** [wallabyjs/console-ninja#100] opened 2023-02-05 17:07 UTC
### Describe the feature you'd like.

Hey, just requesting solid.js support for console ninja asap ! Love console ninja !

**Comment by smcenlly** [comment] 2023-02-08 05:11
Closing as a duplicate of https://github.com/wallabyjs/console-ninja/issues/73.

You had already raised this as a feature request in December 😊.

**Closed by smcenlly** 2023-02-08 05:11 UTC
Labels: enhancement
