### ISSUE TITLE
[Bug]: Output display color is just plain white with very small fonts

### ISSUE THREAD

**Issue by omerson-cruz** [wallabyjs/console-ninja#134] opened 2023-04-24 03:02 UTC
### What happened?

I was expecting that the Output display's color and theme would be similar to what is advertised but mine has only white color and the font is very small. It's even hard to see the "folding" icon (or collapsible icon). 

I event tried chaning color theme of VS code but it doesn't have any effect on the output.

I expected it would be similar to what was advertised for the Log Viewer Pro feature like below

![image](https://user-images.githubusercontent.com/65213312/233891648-940641b0-a458-4494-a319-6e43f0e4351f.png)

My VS Code is connecting to a remote server with Ubuntu on WSL2

### Version

V.0.0.110

### Steps to reproduce (or sample repo)

Attached video is a sample of the issue.

https://user-images.githubusercontent.com/65213312/233890758-87b16eae-2ae5-40fd-9761-35fd113cf8ba.mp4

### Log output

```shell
21:44:34.826 info host starting tools discovery and integration
21:44:34.830 info host found yarn package manager usages in /home/omersonc/ws/entourage-web-local
21:44:34.838 info host updating yarn plugin in /home/omersonc/.yarnrc.yml
21:44:34.843 info host looking for tools to patch
21:44:34.845 info host worker Starting Host Worker...
21:44:36.070 info host found 10 tool file(s) to patch
21:44:36.071 info host patching /home/omersonc/ws/entourage-web-local/node_modules/next/dist/compiled/webpack/bundle5.js
21:44:36.072 info host patching /home/omersonc/ws/entourage-web-local/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
21:44:36.072 info host patching /home/omersonc/ws/entourage-web-local/apps/swr-context/node_modules/next/dist/compiled/webpack/bundle5.js
21:44:36.072 info host patching /home/omersonc/ws/entourage-web-local/components/react/node_modules/next/dist/compiled/webpack/bundle5.js
21:44:36.072 info host patching /home/omersonc/ws/entourage-web-local/apps/swr-context/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
21:44:36.072 info host patching /home/omersonc/ws/entourage-web-local/components/react/node_modules/next/dist/build/webpack/loaders/next-swc-loader.js
21:44:36.101 info host completed tools discovery and integration
21:44:36.102 info host removing cache folder: 24291ba8c71a4caa1a5ce6b4cccae3a8
23:37:06.050 info buildHook-1561 installing build hook for next.js at /home/omersonc/ws/entourage-web-local/apps/site-builder, node v14.18.1
23:37:06.057 info buildHook-1561 allowed tools: next.js, node
23:37:06.058 info buildHook-1561 running tools: next.js
23:37:06.059 info buildHook-1561 installing fs interceptor
23:37:06.178 info host client connected: buildHook { address: '::', family: 'IPv6', port: 39775 }
23:37:06.686 info buildHook-1561 allowed tools: next.js, node
23:37:06.686 info buildHook-1561 running tools: next.js
23:37:10.204 info buildHook-1561 file processed (stat): 7 log points, error handler: false
23:37:10.216 info buildHook-1561 file processed (stat): 13 log points, error handler: false
23:37:10.226 info buildHook-1561 file processed (stat): 2 log points, error handler: false
23:37:10.246 info buildHook-1561 file processed (stat): 6 log points, error handler: false
23:37:10.258 info buildHook-1561 file processed (stat): 6 log points, error handler: false
23:37:10.271 info buildHook-1561 file processed (stat): 9 log points, error handler: false
23:38:13.793 info buildHook-1561 file processed (stat): 19 log points, error handler: false
23:38:13.833 info buildHook-1561 file processed (stat): 7 log points, error handler: false
23:38:13.849 info buildHook-1561 file processed (stat): 9 log points, error handler: false
23:38:13.902 info buildHook-1561 file processed (stat): 0 log points, error handler: false
23:38:13.909 info buildHook-1561 file processed (stat): 0 log points, error handler: false
23:38:16.581 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
23:43:11.954 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
23:48:16.421 info buildHook-1561 file processed (stat): 19 log points, error handler: false
23:49:18.896 info buildHook-1561 file processed (stat): 9 log points, error handler: false
23:50:39.460 info buildHook-1561 file processed (stat): 9 log points, error handler: false
23:50:42.415 info buildHook-1561 file processed (stat): 9 log points, error handler: false
23:51:02.680 info buildHook-1561 file processed (stat): 9 log points, error handler: false
23:51:42.298 info buildHook-1561 file processed (stat): 19 log points, error handler: false
01:23:07.889 info buildHook-1561 file processed (stat): 19 log points, error handler: false
01:23:29.998 info buildHook-1561 file processed (stat): 9 log points, error handler: false
01:24:02.889 info buildHook-1561 file processed (stat): 9 log points, error handler: false
01:24:07.042 info buildHook-1561 file processed (stat): 9 log points, error handler: false
01:24:32.284 info buildHook-1561 file processed (stat): 9 log points, error handler: false
01:24:41.447 info buildHook-1561 file processed (stat): 9 log points, error handler: false
01:25:04.056 info buildHook-1561 file processed (stat): 9 log points, error handler: false
01:25:55.617 info buildHook-1561 file processed (stat): 9 log points, error handler: false
01:26:34.417 info buildHook-1561 file processed (stat): 19 log points, error handler: false
01:26:44.154 info buildHook-1561 file processed (stat): 19 log points, error handler: false
01:26:51.695 info buildHook-1561 file processed (stat): 8 log points, error handler: false
01:27:46.389 info buildHook-1561 file processed (stat): 8 log points, error handler: false
01:32:18.746 info buildHook-1561 file processed (stat): 8 log points, error handler: false
01:32:23.360 info buildHook-1561 file processed (stat): 8 log points, error handler: false
01:36:17.216 info buildHook-1561 file processed (stat): 6 log points, error handler: false
01:36:44.115 info host client disconnected: runtimeHook 1006
01:36:44.116 info host client disconnected: runtimeHook
01:36:44.169 info host client disconnected: buildHook 4100
01:36:44.169 info host client disconnected: buildHook 4100, has clients false
01:36:45.978 info buildHook-3450 installing build hook for next.js at /home/omersonc/ws/entourage-web-local/apps/site-builder, node v14.18.1
01:36:45.983 info buildHook-3450 allowed tools: next.js, node
01:36:45.983 info buildHook-3450 running tools: next.js
01:36:46.445 info host client connected: buildHook { address: '::', family: 'IPv6', port: 39775 }
01:36:45.984 info buildHook-3450 installing fs interceptor
01:36:46.452 info buildHook-3450 allowed tools: next.js, node
01:36:46.452 info buildHook-3450 running tools: next.js
01:36:47.225 info buildHook-3450 file processed (stat): 7 log points, error handler: false
01:36:47.236 info buildHook-3450 file processed (stat): 13 log points, error handler: false
01:36:47.243 info buildHook-3450 file processed (stat): 2 log points, error handler: false
01:36:47.262 info buildHook-3450 file processed (stat): 6 log points, error handler: false
01:36:47.273 info buildHook-3450 file processed (stat): 9 log points, error handler: false
01:36:56.684 info buildHook-3450 file processed (stat): 19 log points, error handler: false
01:36:56.724 info buildHook-3450 file processed (stat): 7 log points, error handler: false
01:36:56.736 info buildHook-3450 file processed (stat): 9 log points, error handler: false
01:36:56.745 info buildHook-3450 file processed (stat): 8 log points, error handler: false
01:36:56.751 info buildHook-3450 file processed (stat): 0 log points, error handler: false
01:36:56.757 info buildHook-3450 file processed (stat): 0 log points, error handler: false
01:36:57.511 info host client disconnected: runtimeHook 1001
01:36:57.511 info host client disconnected: runtimeHook
01:36:58.073 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
01:37:04.730 info host client disconnected: runtimeHook 1001
01:37:04.730 info host client disconnected: runtimeHook
01:37:05.169 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
01:37:06.841 info host client disconnected: runtimeHook 1001
01:37:06.841 info host client disconnected: runtimeHook
01:37:07.283 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
01:37:17.878 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
01:38:13.891 info buildHook-3450 file processed (stat): 5 log points, error handler: false
01:41:04.381 info buildHook-3450 file processed (stat): 6 log points, error handler: false
01:42:03.835 info buildHook-3450 file processed (stat): 6 log points, error handler: false
01:42:44.917 info buildHook-3450 file processed (stat): 8 log points, error handler: false
01:42:56.233 info host client disconnected: runtimeHook 1001
01:42:56.233 info host client disconnected: runtimeHook
01:43:41.574 info buildHook-3450 file processed (stat): 6 log points, error handler: false
01:43:42.460 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
01:45:45.775 info host log viewer state size exceeded max size in entries, clearing it
01:46:02.606 info host log viewer state size exceeded max size in entries, clearing it
01:50:51.502 info buildHook-3450 file processed (stat): 6 log points, error handler: false
01:52:27.316 info buildHook-3450 file processed (stat): 6 log points, error handler: false
01:53:03.681 info buildHook-3450 file processed (stat): 6 log points, error handler: false
01:53:43.000 info buildHook-3450 file processed (stat): 6 log points, error handler: false
01:54:02.191 info buildHook-3450 file processed (stat): 6 log points, error handler: false
01:54:04.924 info buildHook-3450 file processed (stat): 6 log points, error handler: false
01:56:15.094 info host client disconnected: runtimeHook 1006
01:56:15.094 info host client disconnected: runtimeHook
01:56:15.148 info host client disconnected: buildHook 4100
01:56:15.148 info host client disconnected: buildHook 4100, has clients false
08:10:39.865 info buildHook-4544 installing build hook for next.js at /home/omersonc/ws/entourage-web-local/apps/site-builder, node v14.18.1
08:10:39.870 info buildHook-4544 allowed tools: next.js, node
08:10:39.870 info buildHook-4544 running tools: next.js
08:10:40.327 info host client connected: buildHook { address: '::', family: 'IPv6', port: 39775 }
08:10:39.871 info buildHook-4544 installing fs interceptor
08:10:40.331 info buildHook-4544 allowed tools: next.js, node
08:10:40.331 info buildHook-4544 running tools: next.js
08:10:41.067 info buildHook-4544 file processed (stat): 7 log points, error handler: false
08:10:41.076 info buildHook-4544 file processed (stat): 13 log points, error handler: false
08:10:41.083 info buildHook-4544 file processed (stat): 2 log points, error handler: false
08:10:41.098 info buildHook-4544 file processed (stat): 5 log points, error handler: false
08:10:41.109 info buildHook-4544 file processed (stat): 6 log points, error handler: false
08:10:41.119 info buildHook-4544 file processed (stat): 9 log points, error handler: false
08:10:45.021 info buildHook-4544 file processed (stat): 19 log points, error handler: false
08:10:45.062 info buildHook-4544 file processed (stat): 8 log points, error handler: false
08:10:45.076 info buildHook-4544 file processed (stat): 7 log points, error handler: false
08:10:45.089 info buildHook-4544 file processed (stat): 9 log points, error handler: false
08:10:45.096 info buildHook-4544 file processed (stat): 0 log points, error handler: false
08:10:45.103 info buildHook-4544 file processed (stat): 0 log points, error handler: false
08:10:45.788 info host client disconnected: runtimeHook 1001
08:10:45.788 info host client disconnected: runtimeHook
08:10:46.361 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
08:14:02.416 info buildHook-4544 file processed (stat): 9 log points, error handler: false
08:14:18.063 info buildHook-4544 file processed (stat): 9 log points, error handler: false
08:14:27.459 info host client disconnected: runtimeHook 1001
08:14:27.459 info host client disconnected: runtimeHook
08:14:27.921 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
08:16:19.603 info buildHook-4544 file processed (stat): 10 log points, error handler: false
08:17:09.087 info buildHook-4544 file processed (stat): 16 log points, error handler: false
08:18:06.279 info buildHook-4544 file processed (stat): 0 log points, error handler: false
08:18:17.038 info buildHook-4544 file processed (stat): 19 log points, error handler: false
08:18:38.976 info buildHook-4544 file processed (stat): 19 log points, error handler: false
08:19:04.508 info buildHook-4544 file processed (stat): 9 log points, error handler: false
08:20:26.202 info buildHook-4544 file processed (stat): 9 log points, error handler: false
08:21:01.803 info buildHook-4544 file processed (stat): 9 log points, error handler: false
08:21:34.500 info buildHook-4544 file processed (stat): 9 log points, error handler: false
08:21:48.456 info buildHook-4544 file processed (stat): 9 log points, error handler: false
08:21:58.568 info buildHook-4544 file processed (stat): 9 log points, error handler: false
08:22:47.767 info buildHook-4544 file processed (stat): 19 log points, error handler: false
08:23:59.327 info buildHook-4544 file processed (stat): 19 log points, error handler: false
08:24:43.163 info buildHook-4544 file processed (stat): 19 log points, error handler: false
08:25:00.632 info buildHook-4544 file processed (stat): 19 log points, error handler: false
08:25:08.493 info buildHook-4544 file processed (stat): 19 log points, error handler: false
08:25:28.390 info buildHook-4544 file processed (stat): 19 log points, error handler: false
08:26:16.456 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
08:26:43.525 info buildHook-4544 file processed (stat): 19 log points, error handler: false
08:26:54.270 info host client disconnected: runtimeHook 1006
08:26:54.270 info host client disconnected: runtimeHook
08:26:54.318 info host client disconnected: buildHook 4100
08:26:54.318 info host client disconnected: buildHook 4100, has clients false
08:26:55.793 info buildHook-5922 installing build hook for next.js at /home/omersonc/ws/entourage-web-local/apps/site-builder, node v14.18.1
08:26:55.799 info buildHook-5922 allowed tools: next.js, node
08:26:55.799 info buildHook-5922 running tools: next.js
08:26:56.252 info host client connected: buildHook { address: '::', family: 'IPv6', port: 39775 }
08:26:55.800 info buildHook-5922 installing fs interceptor
08:26:56.260 info buildHook-5922 allowed tools: next.js, node
08:26:56.260 info buildHook-5922 running tools: next.js
08:26:56.994 info buildHook-5922 file processed (stat): 7 log points, error handler: false
08:26:57.003 info buildHook-5922 file processed (stat): 13 log points, error handler: false
08:26:57.011 info buildHook-5922 file processed (stat): 2 log points, error handler: false
08:26:57.026 info buildHook-5922 file processed (stat): 5 log points, error handler: false
08:26:57.037 info buildHook-5922 file processed (stat): 6 log points, error handler: false
08:26:57.047 info buildHook-5922 file processed (stat): 9 log points, error handler: false
08:26:57.058 info buildHook-5922 file processed (stat): 9 log points, error handler: false
08:27:05.519 info buildHook-5922 file processed (stat): 19 log points, error handler: false
08:27:05.573 info buildHook-5922 file processed (stat): 7 log points, error handler: false
08:27:05.592 info buildHook-5922 file processed (stat): 19 log points, error handler: false
08:27:05.602 info buildHook-5922 file processed (stat): 8 log points, error handler: false
08:27:05.613 info buildHook-5922 file processed (stat): 0 log points, error handler: false
08:27:05.621 info buildHook-5922 file processed (stat): 0 log points, error handler: false
08:27:06.538 info host client disconnected: runtimeHook 1001
08:27:06.538 info host client disconnected: runtimeHook
08:27:07.053 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
08:28:46.004 info host client connected: runtimeHook { address: '::', family: 'IPv6', port: 39775 }
```

**Comment by smcenlly** [comment] 2023-04-25 23:44
Are you still having the problem? If so, can you please do the following:

1. Confirm the theme you are using (it looks like `One Monokai` fromr your video).
2. Run the VS Code command, `Developer: Generate Color Theme from Current Settings` and provide us with the output.

---

The Console Output will **not** update object highlighting colours until you select a theme. So in your video where you are previewing a theme, Console Output is not expected to change.

If you're still having a problem and you haven't already done this, please try closing and re-opening all VS Code instances. You may also try restarting your PC in case there is a lingering VS Code process (or issue) that's causing the problem.

**Comment by smcenlly** [comment] 2023-04-26 00:50
We have reproduced your problem; there's no need to provide further information previously requested.

**Comment by NikGovorov** [comment] 2023-04-26 10:25
The font size can be changed by using Console-Ninja: Font Size (`console-ninja.fontSize`) setting.

![image](https://user-images.githubusercontent.com/129254/234547702-0a3d6b65-16e3-47c7-b464-c58d3c681d6f.png)

**Comment by omerson-cruz** [comment] 2023-04-26 19:10
Hi @NikGovorov , thank you for your reply. Sorry my bad I missed to see this setting. And yes that setting works on my end. 

Btw for the color on the output window. Is there any way to change it to similar to the color theme on my VS code editor? Or at least have color scheme similar to the one shown in the Marketplace? You know just something to be able to differentiate between key-value pairs on the object that I'm trying to console log especially if it's a large object. 

Thank you for your support!

**Comment by smcenlly** [comment] 2023-04-26 23:00
> Btw for the color on the output window. Is there any way to change it to similar to the color theme on my VS code editor? Or at least have color scheme similar to the one shown in the Marketplace? You know just something to be able to differentiate between key-value pairs on the object that I'm trying to console log especially if it's a large object.

It looks like when the extension is running in a remote workspace, it doesn't have access to themes. We're not sure how to support this scenario yet or why it had broken (perhaps VS Code optimization / update). We're working on it and will post back here when we have an update to share.

**Comment by NikGovorov** [comment] 2023-05-02 03:45
We've added limited support of themes in Log Viewer running in Remote context to Console Ninja v0.0.115.

**Closed by NikGovorov** 2023-05-02 03:45 UTC
Labels: bug

**Comment by omerson-cruz** [comment] 2023-05-02 06:16
Thanks for your support team Wallaby!! I see it's now working! :)
