### ISSUE TITLE
[Feature]: Support for custom loggers

### ISSUE THREAD

**Issue by selfagency** [wallabyjs/console-ninja#199] opened 2023-09-10 23:00 UTC
I don't use `console.log()`, I use a custom logger that has transports including logging to console, albeit with specialized formatting. Is it possible to configure Console Ninja to capture these? Eg., instead of `console.log()` I use `log.info()`. If not, I would love support for this feature.

**Comment by smcenlly** [comment] 2023-09-10 23:23
Closing as a duplicate of https://github.com/wallabyjs/console-ninja/issues/35

**Closed by smcenlly** 2023-09-10 23:23 UTC
Labels: enhancement, requires triage

**Comment by ArtemGovorov** [comment] 2023-09-11 00:27
Until such time the support for custom loggers is added, [logpoints](https://github.com/wallabyjs/console-ninja#logpoints) may be used as a (more powerful) alternative.
